from typing import Dict
from nightKnights.src.interfaces.skill_interface import SynonymMappingInterface

class SynonymMapper(SynonymMappingInterface):
    def __init__(self):
        self.synonym_map: Dict[str, str] = {
            "reactjs": "React",
            "tf 2": "TensorFlow",
            "aws ec2": "AWS",
            "azure devops": "Azure",
            "ms sql": "SQL Server",
            "gcp": "Google Cloud Platform",
            "kubernetes": "Kubernetes",
            "k8s": "Kubernetes",
            "node": "Node.js",
            "expressjs": "Express.js",
            "nextjs": "Next.js",
            "angularjs": "Angular",
            "vuejs": "Vue.js",
            "c sharp": "C#",
            "dot net": ".NET",
            "net": ".NET",
            "rest api": "RESTful API",
            "graphql": "GraphQL",
            "html5": "HTML",
            "css3": "CSS",
            "sass": "Sass",
            "less": "Less",
            "bootstrap": "Bootstrap",
            "tailwind css": "Tailwind CSS",
            "material ui": "Material-UI",
            "ant design": "Ant Design",
            "postgresql": "PostgreSQL",
            "mongodb": "MongoDB",
            "mysql": "MySQL",
            "microsoft sql server": "SQL Server",
            "oracle db": "Oracle Database",
            "dynamodb": "DynamoDB",
            "google cloud": "Google Cloud Platform",
            "amazon web services": "AWS",
            "microsoft azure": "Azure",
            "docker": "Docker",
            "jenkins": "Jenkins",
            "travis ci": "Travis CI",
            "gitlab ci": "GitLab CI",
            "github actions": "GitHub Actions",
            "ansible": "Ansible",
            "puppet": "Puppet",
            "chef": "Chef",
            "terraform": "Terraform",
            "cloudformation": "CloudFormation",
            "machine learning": "Machine Learning",
            "deep learning": "Deep Learning",
            "natural language processing": "NLP",
            "computer vision": "Computer Vision",
            "nlp": "NLP",
            "cv": "Computer Vision",
            "pytorch": "PyTorch",
            "scikit-learn": "Scikit-learn",
            "pandas": "Pandas",
            "numpy": "NumPy",
            "spark": "Apache Spark",
            "hadoop": "Apache Hadoop",
            "kafka": "Apache Kafka",
            "data bricks": "Databricks",
            "snowflake": "Snowflake",
            "tableau": "Tableau",
            "power bi": "Power BI",
            "looker": "Looker",
            "qlikview": "QlikView",
            "git hub": "GitHub",
            "bit bucket": "Bitbucket",
            "gitlab": "GitLab",
            "svn": "SVN",
            "jira": "Jira",
            "confluence": "Confluence",
            "trello": "Trello",
            "asana": "Asana",
            "agile methodologies": "Agile",
            "scrum master": "Scrum",
            "kanban": "Kanban",
            "pmp": "PMP",
            "csm": "CSM",
            "aws certified": "AWS Certified",
            "azure certified": "Azure Certified",
            "google cloud certified": "GCP Certified",
            "communication": "Communication",
            "teamwork": "Teamwork",
            "problem solving": "Problem Solving",
            "critical thinking": "Critical Thinking",
            "adaptability": "Adaptability",
            "leadership": "Leadership",
            "time management": "Time Management",
            "project management": "Project Management",
            "data science": "Data Science",
            "big data": "Big Data",
            "etl": "ETL",
            "data warehousing": "Data Warehousing",
            "data lakes": "Data Lakes",
        }

    def map_synonyms(self, skill: str) -> str:
        return self.synonym_map.get(skill.lower(), skill)
